const dysc_check = require('./tasks/dysc_check');

dysc_check()
console.log('1 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('2 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('3 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('4 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('5 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('6 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('7 dysc_check 1s')
sleep(1000)
dysc_check()
console.log('8 dysc_check 1s')
sleep(1000)
exit()
