const kuaishou_check = require('./tasks/kuaishou_check');

kuaishou_check()
console.log('1 kuaishou_check 1s')
sleep(1000)
kuaishou_check()
console.log('2 kuaishou_check 1s')
sleep(1000)
kuaishou_check()
console.log('3 kuaishou_check 1s')
sleep(1000)
kuaishou_check()
console.log('4 kuaishou_check 1s')
sleep(1000)
kuaishou_check()
console.log('5 kuaishou_check 1s')
sleep(1000)
exit()
