const zfb_check = require('./tasks/zfb_check');

zfb_check()
console.log('1 zfb_check 1s')
sleep(1000)

zfb_check()
console.log('2 zfb_check 1s')
sleep(1000)

zfb_check()
console.log('3 zfb_check 1s')
sleep(1000)
zfb_check()
console.log('4 zfb_check 1s')
sleep(1000)
zfb_check()
console.log('5 zfb_check 1s')
sleep(1000)
zfb_check()
console.log('6 zfb_check 1s')
sleep(1000)
zfb_check()
console.log('7 zfb_check 1s')
sleep(1000)

zfb_check()
console.log('8 zfb_check 1s')
sleep(1000)
exit()
